language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.5
  - 2.3.1
script: "RAILS_ENV=test bundle exec rake test"
env:
  global:
    - RUBYOPT='W0'
  matrix:
    - DB=sqlite
    - DB=mysql
    - DB=postgresql
before_script:
  - mysql -e 'create database lentil_test;'
  - psql -c 'create database lentil_test;' -U postgres
  - "RAILS_ENV=test bundle exec rake db:create db:schema:load"
notifications:
  email:
    - bddavids@ncsu.edu
addons:
  postgresql: "9.4"
