language: ruby
rvm:
  - 1.9.3
  - 2.1.4
script: "bundle exec rake test"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - "RAILS_ENV=test bundle exec rake db:create db:schema:load"
notifications:
  email:
    - jmcasden@ncsu.edu
slack:
  secure: TZ+ysJCJtpO/92dvJanZhBrV41z3Ec45o73OqKyfxE9jdjOziI6axXWRNMYUoDh0O0CvFYtS5q7usXrj0fo9sPCxQovLZICdAfmOaKPwzWAmFIBpcBQuz1JPMpOSBsBi19zfzgutcIyE4Ov2VaNlQKnqjlFU/2HWO92PUV7SNmg=
