language: ruby
rvm:
  - 1.9.3
  - 2.0.0
script: "bundle exec rake test"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - "RAILS_ENV=test bundle exec rake db:create db:schema:load"

